const { test, expect } = require('@playwright/test');
const { runtimeGuard, openApp } = require('./helpers');

async function seed(page, overrides={}){
const fixture={schemaVersion:15,meta:{primaryPortfolioId:'portfolio-1',primaryBuildingId:'building-1',revision:1},property:{name:'G Haus',address:'Testweg 1',totalArea:200,year:'1990'},finance:{repayment:900,fixed:0},correspondence:{landlordName:'Test',landlordAddress:'Testweg 1'},portfolios:[{id:'portfolio-1',name:'Privatbestand',kind:'private'}],buildings:[{id:'building-1',portfolioId:'portfolio-1',name:'G Haus',address:'Testweg 1',totalArea:200,year:'1990'}],units:[{id:'owner-1',buildingId:'building-1',type:'owner',name:'Eigennutzung',area:100,occupancy:[]},{id:'rental-1',buildingId:'building-1',type:'rental',name:'Mietwohnung',area:100,occupancy:[]}],leases:[{id:'lease-1',buildingId:'building-1',unitId:'rental-1',tenantName:'Mieter Neu',tenantAddress:'Testweg 1',start:'2026-01-01',end:'2026-12-31',rent:550,advance:110,terms:[{id:'term-1',effectiveFrom:'2026-01-01',rent:550,advance:110,reason:'Start'}],handover:{}}],sources:[],costPositions:[],meters:[],waterSettlements:[],tasks:[],payments:[],rentAllocations:[],meterReplacements:[],billingWorkflows:[],billingSnapshots:[],containers:[],water:[],audit:[],...overrides};
await page.evaluate(async state=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('mietverwaltung-v6',3);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put({id:'main',data:state});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()},fixture);await page.reload();
}

test('G führt Vertragsstände, explizites Mietkonto und Rücklastschrift revisionsfest', async ({ page })=>{
const guard=runtimeGuard(page);await openApp(page);await seed(page,{payments:[{id:'p-sep',buildingId:'building-1',direction:'income',date:'2026-09-03',amount:660,label:'Überweisung 09/2026'}]});await openApp(page,'#rental/lifecycle');
await expect(page.getByRole('heading',{name:'Historie statt Überschreiben'})).toBeVisible();await expect(page.getByText('Mieter Neu',{exact:true}).first()).toBeVisible();
await page.getByRole('button',{name:'Miete/BK ändern'}).click();await page.locator('#gTermForm input[name="effectiveFrom"]').fill('2026-10-01');await page.locator('#gTermForm input[name="rent"]').fill('575');await page.locator('#gTermForm input[name="advance"]').fill('115');await page.locator('#gTermForm').getByRole('button',{name:'Änderung speichern'}).click();const tenancyCard=page.locator('[data-tenancy-card="lease-1"]');await expect(tenancyCard).toContainText('575,00');await expect(tenancyCard).toContainText('115,00');
await page.getByRole('button',{name:'Zahlung zuordnen'}).click();await page.locator('#gAllocForm input[name="month"]').fill('2026-09');await page.locator('#gAllocForm input[name="total"]').fill('660');await page.locator('#gAllocForm').getByRole('button',{name:'Zuordnen'}).click();await expect(page.locator('#workspaceBody')).toContainText('Bezahlt');
await page.getByRole('button',{name:'Rücklastschrift'}).click();await page.locator('#gReverseForm input[name="date"]').fill('2026-09-08');await page.locator('#gReverseForm input[name="amount"]').fill('660');await page.locator('#gReverseForm').getByRole('button',{name:'Rücklastschrift buchen'}).click();await expect(page.locator('#workspaceBody')).toContainText('Offen');
const saved=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('mietverwaltung-v6',3);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const rec=await new Promise((resolve,reject)=>{const r=db.transaction('state','readonly').objectStore('state').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return rec.data});expect(saved.leases[0].terms).toHaveLength(2);expect(saved.rentAllocations.some(a=>a.sign===-1)).toBeTruthy();expect(saved.payments.some(p=>p.kind==='rent-reversal')).toBeTruthy();guard.assertClean();
});

test('G verkettet Zählerwechsel und zeigt Abrechnungsversionen ohne negative Resets', async ({ page })=>{
const guard=runtimeGuard(page);await openApp(page);await seed(page,{meters:[{id:'main-old',buildingId:'building-1',role:'mainWater',name:'Hauptwasserzähler',number:'M1',unit:'m³',installedAt:'2026-01-01',readings:[{id:'mr0',date:'2026-01-01',value:100}]},{id:'owner-old',buildingId:'building-1',role:'ownerWater',name:'Zwischenzähler Eigennutzung',number:'O1',unit:'m³',installedAt:'2026-01-01',readings:[{id:'or0',date:'2026-01-01',value:20}]}],billingSnapshots:[{id:'snap-1',buildingId:'building-1',leaseId:'lease-1',periodYear:2025,version:1,lease:{id:'lease-1',tenantName:'Mieter Neu'},result:20,createdAt:'2026-03-01T10:00:00Z'},{id:'snap-2',buildingId:'building-1',leaseId:'lease-1',periodYear:2025,version:2,supersedesSnapshotId:'snap-1',correctionReason:'Nachgereichter Beleg',lease:{id:'lease-1',tenantName:'Mieter Neu'},result:10,createdAt:'2026-03-02T10:00:00Z'}]});await openApp(page,'#rental/lifecycle');await expect(page.locator('#workspaceBody')).toContainText('Version 2');
await page.getByRole('button',{name:'Zähler wechseln'}).click();await page.locator('#gMeterForm select[name="oldMeterId"]').selectOption('main-old');await page.locator('#gMeterForm input[name="date"]').fill('2026-06-30');await page.locator('#gMeterForm input[name="oldValue"]').fill('160');await page.locator('#gMeterForm input[name="newNumber"]').fill('M2');await page.locator('#gMeterForm input[name="newValue"]').fill('0');await page.locator('#gMeterForm').getByRole('button',{name:'Wechsel speichern'}).click();await expect(page.locator('#workspaceBody')).toContainText('M1 → M2');
await page.getByRole('button',{name:'Übergabe'}).click();await page.locator('#gHandoverForm select[name="kind"]').selectOption('move-out');await page.locator('#gHandoverForm input[name="date"]').fill('2026-12-31');await page.locator('#gHandoverForm input[name="mainValue"]').fill('70');await page.locator('#gHandoverForm input[name="ownerValue"]').fill('50');await page.locator('#gHandoverForm').getByRole('button',{name:'Übergabe speichern'}).click();
const saved=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('mietverwaltung-v6',3);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const rec=await new Promise((resolve,reject)=>{const r=db.transaction('state','readonly').objectStore('state').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return rec.data});const oldMain=saved.meters.find(m=>m.id==='main-old'),newMain=saved.meters.find(m=>m.predecessorMeterId==='main-old'),owner=saved.meters.find(m=>m.id==='owner-old');expect(oldMain.removedAt).toBe('2026-06-30');expect(newMain).toBeTruthy();expect(saved.meterReplacements.some(r=>r.oldMeterId==='main-old'&&r.newMeterId===newMain.id)).toBeTruthy();const reading=(m,d)=>Number(m.readings.find(r=>r.date===d)?.value);const house=(reading(oldMain,'2026-06-30')-reading(oldMain,'2026-01-01'))+(reading(newMain,'2026-12-31')-reading(newMain,'2026-06-30')),own=reading(owner,'2026-12-31')-reading(owner,'2026-01-01');expect(reading(newMain,'2026-06-30')).toBe(0);expect(house).toBe(130);expect(own).toBe(30);expect(house-own).toBe(100);guard.assertClean();
});
