type AnyRecord=Record<string,any>;
declare const AppLifecycleLedger:any;
declare const AppApplication:any;

export const RENTAL_LIFECYCLE_UI_VERSION=1;

type Ports={
  state:AnyRecord;
  activeBuildingId:string;
  host:HTMLElement;
  esc:(v:any)=>string;
  euro:(v:any)=>string;
  dateDE:(v:any)=>string;
  modal:(title:string,html:string,onReady?:()=>void)=>void;
  closeModal:(force?:boolean)=>boolean;
  formField:(opts:AnyRecord)=>string;
  executeCommand:(type:string,payload:AnyRecord,handler:(payload:AnyRecord)=>any|Promise<any>,options?:AnyRecord)=>Promise<any>;
  rerender:()=>void;
  go:(route:string,sub?:string)=>void;
};

const q=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T|null;
const money=(v:any)=>Math.max(0,Number(v)||0);
const statusLabel=(s:string)=>s==="paid"?"Bezahlt":s==="partial"?"Teilzahlung":s==="missing"?"Offen":s==="overpaid"?"Überzahlt":"–";
const statusClass=(s:string)=>s==="paid"?"good":s==="overpaid"?"good":s==="partial"?"warn":"bad";

function fmtMonth(month:string){const [y,m]=month.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString("de-DE",{month:"short",year:"numeric"})}
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function remainingForPayment(state:AnyRecord,p:AnyRecord){const used=AppLifecycleLedger.paymentAllocations(state,p.id).reduce((s:number,a:AnyRecord)=>s+Number(a.total||0),0);return Math.max(0,Number(p.amount||0)-used)}


export function billingLifecycleContext(state:AnyRecord,year:number,baseClosure:AnyRecord,requestedLeaseId=""){
  AppLifecycleLedger.ensureLifecycleState(state);
  const buildingId=String(state?.meta?.presentationBuildingId||state?.meta?.primaryBuildingId||"");
  const leases=AppLifecycleLedger.leasesForBillingYear(state,year,buildingId);
  const selectedLease=leases.find((l:AnyRecord)=>String(l.id)===String(requestedLeaseId))||leases[0]||baseClosure?.analysis?.lease||null;
  let analysis=baseClosure?.analysis||{},points=[...(baseClosure?.points||[])],ok=!!baseClosure?.ok,lifecycleIssues=[] as AnyRecord[];
  if(selectedLease&&leases.length>1){
    analysis=AppLifecycleLedger.leaseBillingAnalysis(state,analysis,year,String(selectedLease.id));
    points=points.map((x:AnyRecord)=>x.id==="advance"?{...x,ok:Number(analysis.advanceEvidence?.recognizedPayments||0)>0,label:"Vorauszahlungen dieses Mietverhältnisses sind im Mietkonto zugeordnet"}:x);
    lifecycleIssues=(analysis.unresolved||[]).filter((x:AnyRecord)=>![...(baseClosure?.analysis?.unresolved||[])].some((b:AnyRecord)=>b===x||b.id&&b.id===x.id));
    ok=points.every((x:AnyRecord)=>x.ok)&&!(analysis.unresolved||[]).length;
  }
  const selectedLeaseId=String(selectedLease?.id||""),snapshot=AppLifecycleLedger.latestSnapshotFor(state,year,selectedLeaseId);
  return {year,buildingId,leases,selectedLease,selectedLeaseId,analysis,closure:{...baseClosure,analysis,points,ok},snapshot,lifecycleIssues,history:AppLifecycleLedger.billingRevisionHistory(state,year,selectedLeaseId)}
}

export function renderCompactLedger(state:AnyRecord,h:{euro:(v:any)=>string;esc:(v:any)=>string}){
  AppLifecycleLedger.ensureLifecycleState(state);const model=AppLifecycleLedger.rentLedger(state,{buildingId:String(state?.meta?.primaryBuildingId||"")}),rows=model.rows.slice(-12).reverse();
  return `<section id="rentLedger" class="card"><div class="card-head"><div><p class="eyebrow">MIETKONTO</p><h3>Soll, Ist & Zuordnung</h3></div><span class="pill ${model.open>.01?"warn":"good"}">${model.open>.01?`${h.euro(model.open)} offen`:"Ausgeglichen"}</span></div>
  <div class="grid cards"><article class="card metric-card"><span>Soll 12M</span><strong>${h.euro(model.expected)}</strong></article><article class="card metric-card"><span>Zugeordnet</span><strong>${h.euro(model.paid)}</strong></article><article class="card metric-card"><span>Offen</span><strong>${h.euro(model.open)}</strong></article></div>
  <div class="tablewrap"><table class="costtable"><thead><tr><th>Monat</th><th>Soll</th><th>Zugeordnet</th><th>Differenz</th><th>Status</th></tr></thead><tbody>${rows.map((r:AnyRecord)=>`<tr><td>${fmtMonth(r.month)}</td><td>${h.euro(r.total)}</td><td>${h.euro(r.paid)}</td><td>${h.euro(r.difference)}</td><td><span class="pill ${statusClass(r.status)}">${statusLabel(r.status)}</span></td></tr>`).join("")}</tbody></table></div><p class="muted">Das Mietkonto basiert auf zeitanteiligem Soll und expliziten Zahlungszuordnungen. Historische Vertragsdaten bleiben erhalten.</p></section>`
}

function tenancyCard(p:Ports,lease:AnyRecord){
  const {esc,euro,dateDE}=p,terms=(lease.terms||[]).slice().sort((a:AnyRecord,b:AnyRecord)=>String(b.effectiveFrom).localeCompare(String(a.effectiveFrom))),latest=terms[0]||lease,moveIn=lease.handover?.moveIn,moveOut=lease.handover?.moveOut;
  return `<article class="card" data-tenancy-card="${esc(lease.id)}"><div class="card-head"><div><p class="eyebrow">${lease.end?"MIETVERHÄLTNIS":"AKTIVES MIETVERHÄLTNIS"}</p><h3>${esc(lease.tenantName||"Mieter/in")}</h3></div><span class="pill ${lease.end?"":"good"}">${dateDE(lease.start)}${lease.end?` – ${dateDE(lease.end)}`:" – laufend"}</span></div>
    <div class="fact-row"><span>Kaltmiete aktuell</span><strong>${euro(latest.rent)} / Monat</strong></div><div class="fact-row"><span>BK-Vorauszahlung aktuell</span><strong>${euro(latest.advance)} / Monat</strong></div><div class="fact-row"><span>Vertragsstände</span><strong>${terms.length}</strong></div>
    <div class="fact-row"><span>Einzugsübergabe</span><strong>${moveIn?`✓ ${dateDE(moveIn.date)}`:"fehlt"}</strong></div><div class="fact-row"><span>Auszugsübergabe</span><strong>${lease.end?(moveOut?`✓ ${dateDE(moveOut.date)}`:"fehlt"):"–"}</strong></div>
    <div class="row"><button class="secondary compact" data-term="${esc(lease.id)}">Miete/BK ändern</button><button class="secondary compact" data-handover="${esc(lease.id)}">Übergabe</button>${!lease.end?`<button class="secondary compact" data-close-tenancy="${esc(lease.id)}">Auszug</button>`:""}</div>
    ${terms.length>1?`<details class="secondary-detail"><summary>Vertragshistorie</summary><div class="detail-content">${terms.map((t:AnyRecord)=>`<div class="fact-row"><span>${dateDE(t.effectiveFrom)}</span><strong>${euro(t.rent)} + ${euro(t.advance)} BK</strong></div>`).join("")}</div></details>`:""}</article>`
}

function openTenancy(p:Ports){
  const units=(p.state.units||[]).filter((u:AnyRecord)=>u.type==="rental"&&(!p.activeBuildingId||u.buildingId===p.activeBuildingId));
  if(!units.length)return alert("Bitte zuerst eine Mietwohnung anlegen.");
  p.modal("Mietverhältnis anlegen",`<form id="gTenancyForm" class="form-grid">${p.formField({name:"tenantName",label:"Mieter/in",value:""})}${p.formField({name:"tenantAddress",label:"Korrespondenzadresse",value:"",full:true})}${p.formField({name:"unitId",label:"Mietwohnung",type:"select",value:units[0].id,options:units.map((u:AnyRecord)=>({value:u.id,label:u.name||"Mietwohnung"}))})}${p.formField({name:"start",label:"Vertragsbeginn",type:"date",value:""})}${p.formField({name:"end",label:"Vertragsende (optional)",type:"date",value:""})}${p.formField({name:"rent",label:"Kaltmiete €",type:"number",step:"0.01",min:0,value:""})}${p.formField({name:"advance",label:"BK-Vorauszahlung €",type:"number",step:"0.01",min:0,value:""})}${p.formField({name:"note",label:"Notiz",value:"",full:true})}<div class="full form-actions"><button class="primary">Anlegen</button></div></form>`,()=>{
    const form=q<HTMLFormElement>("gTenancyForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));const result=await p.executeCommand("tenancy.create",v,()=>AppApplication.createTenancyCommand(p.state,v,{buildingId:p.activeBuildingId,unitId:String(v.unitId||"")} ),{auditText:"Mietverhältnis angelegt",restorePoint:true});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}
  })
}
function openTerm(p:Ports,lease:AnyRecord){const latest=AppLifecycleLedger.leaseTermAt(lease,new Date().toISOString().slice(0,10));p.modal("Miete / Vorauszahlung ändern",`<form id="gTermForm" class="form-grid">${p.formField({name:"effectiveFrom",label:"Gültig ab",type:"date",value:""})}${p.formField({name:"rent",label:"Kaltmiete €",type:"number",step:"0.01",min:0,value:latest.rent})}${p.formField({name:"advance",label:"BK-Vorauszahlung €",type:"number",step:"0.01",min:0,value:latest.advance})}${p.formField({name:"reason",label:"Grund / Notiz",value:"Anpassung",full:true})}<div class="full info">Der bisherige Vertragsstand wird nicht überschrieben. Ab dem Stichtag entsteht ein neuer historischer Vertragsstand.</div><div class="full form-actions"><button class="primary">Änderung speichern</button></div></form>`,()=>{const form=q<HTMLFormElement>("gTermForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));const payload={...v,leaseId:lease.id,rent:money(v.rent),advance:money(v.advance)};const result=await p.executeCommand("tenancy.term.add",payload,()=>AppApplication.addLeaseTermCommand(p.state,payload),{auditText:"Vertragsstand ergänzt",restorePoint:true});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}})}
function openClose(p:Ports,lease:AnyRecord){p.modal("Auszug erfassen",`<form id="gCloseForm" class="form-grid">${p.formField({name:"end",label:"Vertragsende / Auszug",type:"date",value:lease.end||""})}${p.formField({name:"note",label:"Notiz",value:"",full:true})}<div class="full legal-warn"><strong>Danach Übergabestände erfassen.</strong><br>Die App trennt Soll, Vorauszahlungen und Verbrauch am Auszugsdatum.</div><div class="full form-actions"><button class="primary">Auszug speichern</button></div></form>`,()=>{const form=q<HTMLFormElement>("gCloseForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form)),payload={...v,leaseId:lease.id};const result=await p.executeCommand("tenancy.close",payload,()=>AppApplication.closeTenancyCommand(p.state,payload),{auditText:"Mietverhältnis beendet",restorePoint:true});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}})}
function openHandover(p:Ports,lease:AnyRecord){
  const canOut=!!lease.end,kind=canOut&&!lease.handover?.moveOut?"move-out":"move-in",date=kind==="move-out"?lease.end:lease.start;
  p.modal(kind==="move-out"?"Auszugsübergabe":"Einzugsübergabe",`<form id="gHandoverForm" class="form-grid"><label><span>Art</span><select name="kind"><option value="move-in" ${kind==="move-in"?"selected":""}>Einzug</option>${canOut?`<option value="move-out" ${kind==="move-out"?"selected":""}>Auszug</option>`:""}</select></label>${p.formField({name:"date",label:"Übergabedatum",type:"date",value:date})}${p.formField({name:"persons",label:"Personenzahl",type:"number",step:"1",min:0,value:""})}${p.formField({name:"mainValue",label:"Hauptwasserzähler",type:"number",step:"0.001",value:""})}${p.formField({name:"ownerValue",label:"Zwischenzähler Eigennutzung",type:"number",step:"0.001",value:""})}${p.formField({name:"note",label:"Notiz",value:"",full:true})}<div class="full info">Für eine saubere Kaltwassertrennung bei Mieterwechseln werden beide Zählerstände am selben Übergabedatum gespeichert.</div><div class="full form-actions"><button class="primary">Übergabe speichern</button></div></form>`,()=>{const form=q<HTMLFormElement>("gHandoverForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form)),payload={leaseId:lease.id,kind:v.kind,date:v.date,persons:Number(v.persons)||0,note:v.note,readings:[{role:"mainWater",value:Number(v.mainValue)},{role:"ownerWater",value:Number(v.ownerValue)}]};const result=await p.executeCommand("tenancy.handover",payload,()=>AppApplication.recordHandoverCommand(p.state,payload),{auditText:"Übergabe dokumentiert",restorePoint:true});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}})
}
function openAllocation(p:Ports){
  const payments=(p.state.payments||[]).filter((x:AnyRecord)=>x.direction==="income"&&remainingForPayment(p.state,x)>.01),leases=(p.state.leases||[]).filter((l:AnyRecord)=>!p.activeBuildingId||l.buildingId===p.activeBuildingId);if(!payments.length)return alert("Keine noch zuzuordnende Einnahme vorhanden.");if(!leases.length)return alert("Kein Mietverhältnis vorhanden.");
  p.modal("Mietzahlung zuordnen",`<form id="gAllocForm" class="form-grid"><label class="full"><span>Zahlung</span><select name="paymentId">${payments.map((x:AnyRecord)=>`<option value="${p.esc(x.id)}">${p.esc(x.date)} · ${p.euro(remainingForPayment(p.state,x))} frei · ${p.esc(x.label||"")}</option>`).join("")}</select></label><label class="full"><span>Mietverhältnis</span><select name="leaseId">${leases.map((l:AnyRecord)=>`<option value="${p.esc(l.id)}">${p.esc(l.tenantName||l.id)}</option>`).join("")}</select></label>${p.formField({name:"month",label:"Mietmonat",type:"month",value:currentMonth()})}${p.formField({name:"total",label:"Betrag €",type:"number",step:"0.01",min:0,value:""})}<div class="full info">Die App ordnet den Betrag zuerst der Kaltmiete und danach der BK-Vorauszahlung des gewählten Monats zu. Eine Zahlung kann anschließend auf weitere Monate verteilt werden.</div><div class="full form-actions"><button class="primary">Zuordnen</button></div></form>`,()=>{const form=q<HTMLFormElement>("gAllocForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form)),payment=p.state.payments.find((x:AnyRecord)=>x.id===v.paymentId),total=money(v.total)||remainingForPayment(p.state,payment),payload={paymentId:v.paymentId,allocations:[{leaseId:v.leaseId,month:v.month,total}]};const existing=AppLifecycleLedger.paymentAllocations(p.state,String(v.paymentId));if(existing.length)payload.allocations=[...existing.map((a:AnyRecord)=>({leaseId:a.leaseId,month:a.month,rentAmount:a.rentAmount,advanceAmount:a.advanceAmount,total:a.total})),...payload.allocations];const result=await p.executeCommand("rent.allocate",payload,()=>AppApplication.allocateRentPaymentCommand(p.state,payload),{auditText:"Mietzahlung zugeordnet"});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}})
}
function openReversal(p:Ports){const candidates=(p.state.payments||[]).filter((x:AnyRecord)=>x.direction==="income"&&AppLifecycleLedger.paymentAllocations(p.state,x.id).length);if(!candidates.length)return alert("Keine zugeordnete Mietzahlung für eine Rücklastschrift vorhanden.");p.modal("Rücklastschrift erfassen",`<form id="gReverseForm" class="form-grid"><label class="full"><span>Ursprüngliche Zahlung</span><select name="paymentId">${candidates.map((x:AnyRecord)=>`<option value="${p.esc(x.id)}">${p.esc(x.date)} · ${p.euro(x.amount)} · ${p.esc(x.label||"")}</option>`).join("")}</select></label>${p.formField({name:"date",label:"Rücklastschrift am",type:"date",value:new Date().toISOString().slice(0,10)})}${p.formField({name:"amount",label:"Betrag € (leer = vollständig)",type:"number",step:"0.01",min:0,value:""})}${p.formField({name:"label",label:"Bezeichnung",value:"Rücklastschrift Miete",full:true})}<div class="full legal-warn">Die ursprüngliche Buchung wird nicht gelöscht. Die Rücklastschrift erhält eine negative Gegenbuchung im Mietkonto.</div><div class="full form-actions"><button class="primary">Rücklastschrift buchen</button></div></form>`,()=>{const form=q<HTMLFormElement>("gReverseForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form)),payload={...v,amount:v.amount?Number(v.amount):undefined};const result=await p.executeCommand("rent.reversal",payload,()=>AppApplication.createRentReversalCommand(p.state,payload,{buildingId:p.activeBuildingId}),{auditText:"Miet-Rücklastschrift erfasst",restorePoint:true});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}})}
function openReplacement(p:Ports){const meters=(p.state.meters||[]).filter((m:AnyRecord)=>!m.removedAt&&["mainWater","ownerWater"].includes(m.role));if(!meters.length)return alert("Kein aktiver Wasserzähler vorhanden.");p.modal("Zähler wechseln",`<form id="gMeterForm" class="form-grid"><label class="full"><span>Ausgebauter Zähler</span><select name="oldMeterId">${meters.map((m:AnyRecord)=>`<option value="${p.esc(m.id)}">${p.esc(m.name)} · ${p.esc(m.number||"ohne Nummer")}</option>`).join("")}</select></label>${p.formField({name:"date",label:"Wechseldatum",type:"date",value:""})}${p.formField({name:"oldValue",label:"Ausbaustand",type:"number",step:"0.001",value:""})}${p.formField({name:"newNumber",label:"Neue Zählernummer",value:""})}${p.formField({name:"newValue",label:"Einbaustand",type:"number",step:"0.001",value:"0"})}${p.formField({name:"reason",label:"Grund / Notiz",value:"Zählerwechsel",full:true})}<div class="full info">Alter Zähler und neuer Zähler werden als getrennte Geräte verkettet. Verbrauch wird über beide Geräte addiert; ein neuer Zähler darf deshalb wieder bei 0 starten.</div><div class="full form-actions"><button class="primary">Wechsel speichern</button></div></form>`,()=>{const form=q<HTMLFormElement>("gMeterForm")!;form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form)),payload={...v,oldValue:Number(v.oldValue),newValue:Number(v.newValue)};const result=await p.executeCommand("meter.replace",payload,()=>AppApplication.recordMeterReplacementCommand(p.state,payload),{auditText:"Zählerwechsel dokumentiert",restorePoint:true});if(!result.ok)return alert(result.message);p.closeModal(true);p.rerender()}})}

export function renderRentalLifecycle(p:Ports){
  AppLifecycleLedger.ensureLifecycleState(p.state);const m=AppApplication.lifecycleWorkspaceModel(p.state,{buildingId:p.activeBuildingId}),rows=m.ledger.rows.slice(-18).reverse(),unallocated=(p.state.payments||[]).filter((x:AnyRecord)=>x.direction==="income"&&remainingForPayment(p.state,x)>.01);
  p.host.innerHTML=`<div class="grid cards"><article class="card metric-card"><span>Mietverhältnisse</span><strong>${m.leases.length}</strong><small>${m.active?`${p.esc(m.active.tenantName||"aktiv")}`:"aktuell keines"}</small></article><article class="card metric-card"><span>Offener Sollsaldo</span><strong>${p.euro(m.ledger.open)}</strong><small>explizites Mietkonto</small></article><article class="card metric-card"><span>Nicht zugeordnete Einnahmen</span><strong>${unallocated.length}</strong><small>noch im Mietkonto prüfen</small></article><article class="card metric-card"><span>Zählerwechsel</span><strong>${m.replacements.length}</strong><small>historisch verkettet</small></article></div>
  ${m.alerts.length?`<section class="card"><div class="card-head"><div><p class="eyebrow">HANDLUNGSBEDARF</p><h3>${m.alerts.length} Lifecycle-Hinweis(e)</h3></div></div>${m.alerts.slice(0,6).map((a:AnyRecord)=>`<div class="legal-warn"><strong>${p.esc(a.title)}</strong><br>${p.esc(a.detail)}</div>`).join("")}</section>`:"<div class='legal-ok'><strong>Lifecycle vollständig</strong><br>Aktuell fehlen keine Übergabe- oder Mietkonto-Schritte.</div>"}
  <section class="card"><div class="card-head"><div><p class="eyebrow">MIETVERHÄLTNISSE</p><h3>Historie statt Überschreiben</h3></div><button id="gAddTenancy" class="primary compact">Mietverhältnis</button></div><p class="muted">Mieterwechsel und Änderungen von Kaltmiete/BK werden mit Stichtag gespeichert. Alte Abrechnungsjahre behalten ihren damaligen Vertragsstand.</p></section>${m.leases.map((l:AnyRecord)=>tenancyCard(p,l)).join("")||"<div class='empty-state'><strong>Noch kein Mietverhältnis</strong><p>Lege das erste Mietverhältnis an.</p></div>"}
  <section class="card"><div class="card-head"><div><p class="eyebrow">MIETKONTO</p><h3>Monatliches Soll gegen echte Zahlungen</h3></div><div class="row"><button id="gAllocate" class="primary compact">Zahlung zuordnen</button><button id="gReverse" class="secondary compact">Rücklastschrift</button></div></div><div class="tablewrap"><table class="costtable"><thead><tr><th>Monat</th><th>Mieter/in</th><th>Soll</th><th>Zugeordnet</th><th>Differenz</th><th>Status</th></tr></thead><tbody>${rows.map((r:AnyRecord)=>`<tr><td>${fmtMonth(r.month)}</td><td>${p.esc(r.tenantName)}</td><td>${p.euro(r.total)}</td><td>${p.euro(r.paid)}</td><td>${p.euro(r.difference)}</td><td><span class="pill ${statusClass(r.status)}">${statusLabel(r.status)}</span></td></tr>`).join("")}</tbody></table></div></section>
  <section class="card"><div class="card-head"><div><p class="eyebrow">ZÄHLER-LIFECYCLE</p><h3>Gerätewechsel ohne Verbrauchssprung</h3></div><button id="gReplaceMeter" class="primary compact">Zähler wechseln</button></div>${m.replacements.length?m.replacements.map((r:AnyRecord)=>{const old=p.state.meters.find((x:AnyRecord)=>x.id===r.oldMeterId),fresh=p.state.meters.find((x:AnyRecord)=>x.id===r.newMeterId);return`<div class="fact-row"><span>${p.dateDE(r.date)} · ${p.esc(old?.name||r.role)}</span><strong>${p.esc(old?.number||"alt")} → ${p.esc(fresh?.number||"neu")}</strong></div>`}).join(""):"<p class='muted'>Noch kein Zählerwechsel dokumentiert.</p>"}</section>
  <section class="card"><div class="card-head"><div><p class="eyebrow">ABRECHNUNGSVERSIONEN</p><h3>Revisionshistorie</h3></div><button id="gOpenBilling" class="secondary compact">Abrechnung öffnen</button></div>${m.snapshots.length?m.snapshots.slice(0,12).map((s:AnyRecord)=>`<div class="fact-row"><span>${s.periodYear} · ${p.esc(s.lease?.tenantName||"Mietverhältnis")} · Version ${Number(s.version||1)}</span><strong>${p.euro(s.result)}</strong></div>`).join(""):"<p class='muted'>Noch keine eingefrorene Abrechnung vorhanden.</p>"}</section>`;
  q("gAddTenancy")!.onclick=()=>openTenancy(p);q("gAllocate")!.onclick=()=>openAllocation(p);q("gReverse")!.onclick=()=>openReversal(p);q("gReplaceMeter")!.onclick=()=>openReplacement(p);q("gOpenBilling")!.onclick=()=>p.go("rental","billing");
  document.querySelectorAll<HTMLElement>("[data-term]").forEach(b=>b.onclick=()=>{const l=p.state.leases.find((x:AnyRecord)=>x.id===b.dataset.term);if(l)openTerm(p,l)});document.querySelectorAll<HTMLElement>("[data-close-tenancy]").forEach(b=>b.onclick=()=>{const l=p.state.leases.find((x:AnyRecord)=>x.id===b.dataset.closeTenancy);if(l)openClose(p,l)});document.querySelectorAll<HTMLElement>("[data-handover]").forEach(b=>b.onclick=()=>{const l=p.state.leases.find((x:AnyRecord)=>x.id===b.dataset.handover);if(l)openHandover(p,l)})
}
