/* ===== tests.js ===== */

function assert(name,cond){return{name,ok:!!cond}}
function runSelfTests(){
  const results=[];
  results.push(assert("Standardperiode startet 01.04.",periodStart(2025)==="2025-04-01"));
  results.push(assert("Standardperiode endet 31.03.",periodEnd(2025)==="2026-03-31"));
  results.push(assert("Schaltjahr 2028",daysInclusive("2028-01-01","2028-12-31")===366));
  results.push(assert("März bleibt trotz Sommerzeit 31 Kalendertage",daysInclusive("2027-03-01","2027-03-31")===31));
  results.push(assert("Date-only Vortag bleibt DST-sicher",dateOnlyAddDays("2026-09-01",-1)==="2026-08-31"));
  results.push(assert("Monatsende bleibt lokales Kalenderdatum",localMonthEndISO(new Date(2026,2,1))==="2026-03-31"));
  const dstState=createEmptyState();dstState.property.billingTakeoverDate="2027-04-01";dstState.leases=[{id:"dst-lease",start:"2027-04-01",end:"",rent:500,advance:150,tenantName:"DST-Test"}];
  results.push(assert("12 Monate Vorauszahlung DST-sicher",Math.abs(monthlyAdvanceInPeriod(dstState,dstState.leases[0],2027)-1800)<0.01));
  const v18Leap=createEmptyState();v18Leap.property={...v18Leap.property,totalArea:200,billingTakeoverDate:"2026-04-01"};v18Leap.units=[{id:"o",type:"owner",area:100,occupancy:[]},{id:"r",type:"rental",area:100,occupancy:[]}];v18Leap.costPositions=[positionDefaults({id:"ins-leap",label:"Gebäudeversicherung",category:"insurance",amount:1000,serviceStart:"2026-04-01",serviceEnd:"2027-03-31",assignment:"house",agreement:"area",confirmed:true})];const leapForecast=v18CategoryForecast(v18Leap,2027,{category:"insurance",label:"Gebäudeversicherung",route:"data",sub:"positions"});results.push(assert("V18 Volljahresprognose ignoriert Schaltjahr-Differenz",Math.abs(leapForecast.amount-500)<0.01));
  const v18Partial=createEmptyState();v18Partial.property={...v18Partial.property,totalArea:200,billingTakeoverDate:"2026-09-01"};v18Partial.units=[{id:"o",type:"owner",area:100,occupancy:[]},{id:"r",type:"rental",area:100,occupancy:[]}];v18Partial.leases=[{id:"l",start:"2026-09-01",end:"",rent:400,advance:125,tenantName:"V18"}];results.push(assert("V18 Teilperiode plant 7 BK-Vorauszahlungen",Math.abs(monthlyAdvanceInPeriod(v18Partial,v18Partial.leases[0],2026)-875)<0.01));
  const paidAdvanceState=createEmptyState();paidAdvanceState.property.billingTakeoverDate="2027-04-01";paidAdvanceState.leases=[{id:"paid-lease",start:"2027-04-01",end:"",rent:500,advance:150,tenantName:"Ist-Test"}];paidAdvanceState.payments=[];for(let i=0;i<12;i++){const d=new Date(Date.UTC(2027,3+i,3)),date=d.toISOString().slice(0,10);paidAdvanceState.payments.push({date,direction:"income",amount:i===5?500:650,label:"Miete Ist-Test"})}results.push(assert("Ist-Vorauszahlungen statt Vertragssoll",Math.abs(actualAdvanceInPeriod(paidAdvanceState,paidAdvanceState.leases[0],2027)-1650)<0.01));
  const s=createEmptyState();s.property.totalArea=200;s.units=[{type:"owner",area:100,occupancy:[{from:"2025-01-01",to:"",count:2}]},{type:"rental",area:100,occupancy:[{from:"2025-01-01",to:"",count:2}]}];s.leases=[{id:"lease-test",start:"2025-07-01",end:"",rent:500,advance:150,tenantName:"Testperson"}];
  results.push(assert("Wohnfläche 50/50",Math.abs(shares(s,"2025-07-01").area-.5)<1e-9));results.push(assert("Personen 50/50",Math.abs(shares(s,"2025-07-01").persons-.5)<1e-9));
  s.property.billingTakeoverDate="2025-07-01";s.property.predecessorBillingEnd="2025-06-30";const bp=billingPeriodInfo(s,2025),next=billingPeriodInfo(s,2026);
  results.push(assert("Übernahmeperiode beginnt am gespeicherten Datum",bp.start==="2025-07-01"&&bp.end==="2026-03-31"&&bp.isTakeoverPeriod));results.push(assert("Folgeperiode wieder jährlich",next.start==="2026-04-01"&&next.end==="2027-03-31"&&!next.isTakeoverPeriod));results.push(assert("Vorauszahlung Teilperiode korrekt",Math.abs(monthlyAdvanceInPeriod(s,s.leases[0],2025)-1350)<0.01));
  const oldPos=positionDefaults({label:"Vor Übernahme",category:"waste",amount:100,serviceStart:"2025-04-01",serviceEnd:"2025-06-30",assignment:"house",confirmed:true});results.push(assert("Kosten vor Übernahme ausgeschlossen",positionToEvents(s,oldPos,2025).length===0));
  s.costPositions=[positionDefaults({label:"Gemeinsame Kosten",category:"propertyTax",amount:100,serviceStart:"2025-07-01",serviceEnd:"2026-03-31",assignment:"house",confirmed:true})];results.push(assert("Zentrale Kostenposition 50/50",Math.abs(centralBillingAnalysis(s,2025).tenantCosts-50)<0.01));results.push(assert("Aktuelles Datenschema",SCHEMA_VERSION===13));
  const mt={meters:[{id:"m1",name:"Haupt",number:"MTR120456",readings:[{id:"r1",date:"2025-07-01",value:75}]},{id:"m2",name:"Eigen",number:"SUB654321",readings:[]}]},ma=analyzeMeterOCRText(mt,"MTR12O456\nZählerstand 00075,123 m3","");
  results.push(assert("Zählernummer toleriert OCR-Verwechslung",ma.meterId==="m1"));results.push(assert("Zählerfoto erkennt Dezimalstand",Math.abs(ma.reading-75.123)<0.001));const ranked=rankMeterCandidates(mt,"m1","2025-07-05",meterReadingCandidates("00075123","Kontrast",.76));results.push(assert("Fehlende Dezimalstelle rekonstruiert",ranked[0]&&Math.abs(ranked[0].value-75.123)<.001));
  results.push(assert("Dokumenten-Inbox Neu",documentWorkflowState({analysis:{status:"queued"}})==="new"));results.push(assert("Dokumenten-Inbox Prüfen",documentWorkflowState({analysis:{status:"done",fields:{positionProposals:[{id:"x"}]}}})==="review"));results.push(assert("Kostenposition besitzt Herkunft",!!positionDefaults({label:"Test",amount:1,confirmed:true,origin:"manual"}).provenance));
  const px=positionDefaults({label:"Niederschlagswasser",amount:44.94,confirmed:true,sourceId:"s1"}),ps={...createEmptyState(),sources:[{id:"s1",name:"Kommunalverwaltung Beispielstadt",amount:44.94,dueDates:["2025-11-15"]}],costPositions:[px],payments:[]};results.push(assert("Zahlungsabgleich starker Treffer",paymentMatchScore(ps,{direction:"outflow",amount:44.94,label:"Kommunalverwaltung Niederschlagswasser",date:"2025-11-15"},px).score>=80));results.push(assert("Quellen-Zahlungsabgleich",sourcePaymentMatchScore(ps,{direction:"outflow",amount:44.94,label:"Kommunalverwaltung Beispielstadt",date:"2025-11-15"},ps.sources[0]).score>=70));
  const c=parseBankCSV("Buchungstag;Betrag;Verwendungszweck\n05.08.2025;-44,94;Gebühr\n06.08.2025;650,00;Miete Testperson");results.push(assert("Bank-CSV Ein-/Ausgang",c.rows.length===2&&c.rows[0].direction==="outflow"&&c.rows[1].direction==="income"));
  const rentState={leases:[{id:"l1",start:"2025-01-01",end:"",rent:500,advance:150,tenantName:"Testperson"}],payments:[{date:smartMonthKey()+"-05",direction:"income",amount:650,label:"Miete Testperson"}]};results.push(assert("Mietmonitor erkennt Vollzahlung",rentMonthStatus(rentState).status==="paid"));
  results.push(assert("Smart-Klassifikation Niederschlagswasser",smartClassifyCostText("Niederschlagswasser 44,94 EUR").category==="rainwater"));results.push(assert("Navigation fünf Hauptbereiche",new Set(Object.keys(ROUTE_LABELS)).size===5));results.push(assert("Mietvertrag unter Vermietung",CHECK_INPUT_MAP["Mietvertrag fehlt"]?.route==="rental"));results.push(assert("Detailseiten besitzen Elternbereiche",visibleSub("data","positions")==="costs"&&visibleSub("owner","reconciliation")==="payments"));results.push(assert("Nur zentraler Abrechnungsweg",typeof sourceToEvents==="undefined"&&typeof allocateEvent==="undefined"&&typeof workflowView==="undefined"));
  results.push(assert("Konfidenz verständlich gestuft",confidenceBand(92).id==="high"&&confidenceBand(60).id==="medium"&&confidenceBand(30).id==="low"));results.push(assert("Datenqualität sprachlich gestuft",qualityBand(91).label==="Sehr gut"&&qualityBand(50).label==="Unvollständig"));results.push(assert("Entscheidungs-UX aktiv",DECISION_UI_VERSION===1));
  
  results.push(assert("Fristberechnung nutzt ISO-Datum",periodDeadlineISO(2025)==="2027-03-31"&&periodDeadline(2025)==="31.03.2027"));
  results.push(assert("Zuordnung wird menschenlesbar",assignmentLabel("house")==="gesamtes Haus"&&agreementLabel("area")==="Wohnfläche"));
  results.push(assert("Konfidenz 0–1 wird korrekt normalisiert",confidencePercent(.82)===82));
  const taskStateBackup=state;
  results.push(assert("Premium-Entscheidungsqueue aktiv",typeof smartDecisionQueue==="function"));
  results.push(assert("Meter-Crop besitzt Tipp-Alternative",typeof adjustMeterCrop==="function"));
return results
}


